project:
  type: book

lang: es

book:
  title: "Apuntes de Juegos en Red"
  author: "Rubén Rodríguez Fernández (&#64;rrunix)"
  date: "12/09/2025"
  chapters:
    - index.qmd
    - part: "Introducción a redes"
      chapters:
      - ch/part_networks/network_intro/network_intro.qmd
      - ch/part_networks/access_layer/access_layer.qmd
      - ch/part_networks/network_layer/network_layer.qmd
      - ch/part_networks/transport_layer/transport_layer.qmd
      - ch/part_networks/application_layer/application_layer.qmd

    - part: "Desarrollo en el cliente"

    - part: "Desarrollo en el servidor y comunicación"

    - references.qmd

bibliography: references.bib

format:
  html:
    number-sections: true
    theme:
      - cerulean
  # pdf:
  #   documentclass: scrreprt
  #   lof: true
  #   mermaid:
  #     theme: base
  #     format: svg
  #   css: |
  #     .mermaid {
  #       page-break-inside: avoid;
  #       width: 100%;
  #       height: auto;
  #     }