# Preface {.unnumbered}

Apuntes de la asignatura Juegos en Red. Se organizan en 4 partes:

- Introducción a las redes de computadores. Ofrece una visión general de cómo funcionan las redes de computadores, tanto la parte hardware como software, utilizando la categorización de la pila de protocolos TCP/IP. Esta parte además tendrá una serie de visualizaciones y "Juegos" que podréis encontrar en [jergames.dslabapps.es](https://jergames.dslabapps.es)

- Breve introducción a HTML, CSS, JS y Phaser con el que crearemos un juego web que al que se le añadirán funcionalidades de red en los próximas partes.

- Comunicación entre clientes y servidores a través de APIs REST.

- Comunicación asíncrona entre clientes y servidores.


::: {.callout-important}
Nota: En la parte de redes de computadores, muchos conceptos debido a la naturaleza introductoria de este curso. Esta simplificación se ve realizada por omisión, por ejemplo, se cuentan las variantes antiguas pero no las más nuevas que son más complejas, o por incompletitud, ignorando alguna parte de tecnologías o protocolos que dificultarían su explicación.
:::