timeline
    title Evolución de Internet: De ARPANET a la Era Digital
    
    section Era ARPANET (1969-1983)
        1969 : Nace ARPANET
             : 4 nodos iniciales (UCLA, Stanford, UC Santa Bárbara, Utah)
             : Implementación de conmutación de paquetes
        
        1973 : Primera conexión internacional
        
        1983 : Adopción oficial de TCP/IP
             : División de ARPANET (creación de MILNET)
             : Nace el término "Internet"

    section Nacimiento de la Web (1989-1995)
        1989-1990 : Tim Berners-Lee inventa la World Wide Web
                  : Desarrollo de HTTP, HTML y URLs
        
        1991 : Primer sitio web público

    section Era Comercial (1995-2000)
        1995 : Eliminación de restricciones comerciales
             : Primeros ISPs comerciales (AOL)
             : Aparecen Amazon y eBay
        
        1998 : Fundación de Google
        
        2000-2001 : Explosión de la burbuja punto-com

    section Web 2.0 y Redes Sociales (2003-2010)
        2003-2006 : Redes sociales
        2007 : Lanzamiento del iPhone

    section Era Moderna (2010-2025)
        2010s : Computación en la nube, Internet de las cosas
        
        2020s : Inteligencia Artificial
              : Tecnología 5G
