# Software utilizado en la asignatura {#sec-code}

## Visualizaciones

**Ubicación**: [jergames.dslabapps.es](https://jergames.dslabapps.es)

**Descripción**: Página web con visualizaciones interactivas que incluye:

- Juego del Router: Simula protocolos de enrutamiento y reenvío de paquetes
- CIDR y Coincidencia de Prefijo Más Largo: Comprende el enmascaramiento de subredes y las decisiones de enrutamiento
- Distribución Estática de Ancho de Banda TCP: Visualiza el reparto de ancho de banda entre conexiones TCP
- Distribución Dinámica de Ancho de Banda TCP: Simulación interactiva de asignación de ancho de banda

**Identificador SWH**:
```
swh:1:dir:e759621272f530009eb589570687a2d56d0d4bcd;
origin=https://github.com/rrunix/jer-visualizations;
visit=swh:1:snp:486873193776051caea0e315d0a88a076d0ce242;
anchor=swh:1:rev:3f99cd855ca1298ff61620308ba51d1dd37b7a41
```

**Enlace permanente**: [Software Heritage Archive](https://archive.softwareheritage.org/swh:1:dir:e759621272f530009eb589570687a2d56d0d4bcd;origin=https://github.com/rrunix/jer-visualizations;visit=swh:1:snp:486873193776051caea0e315d0a88a076d0ce242;anchor=swh:1:rev:3f99cd855ca1298ff61620308ba51d1dd37b7a41)

## Libro

**Ubicación**: [GitHub Repository](https://github.com/rrunix/jer-material-abierto)

**Descripción**: Repositorio completo del proyecto de la asignatura que incluye:

- Código fuente de los apuntes de clase (Quarto) + ejemplos. 
- Transparencias del curso (PDF)
- Ejercicios prácticos (Quarto + código)
- Soluciones a los ejercicios (Quarto + código)
- Código de apoyo y ejemplos complementarios

**Identificador SWH**:

```
swh:1:dir:33cb3e030de44f6876bdd6abb3f24dd937d25606;
origin=https://github.com/rrunix/jer-material-abierto;
visit=swh:1:snp:317a2a13c60f4703d57f45bd494d65b6a44cd3ed;
anchor=swh:1:rev:2e7a212b30adaebaa8a1c6a2f0655a1ddc74c496
```

**Enlace permanente**: [Software Heritage Archive](https://archive.softwareheritage.org/swh:1:dir:33cb3e030de44f6876bdd6abb3f24dd937d25606;origin=https://github.com/rrunix/jer-material-abierto;visit=swh:1:snp:317a2a13c60f4703d57f45bd494d65b6a44cd3ed;anchor=swh:1:rev:2e7a212b30adaebaa8a1c6a2f0655a1ddc74c496)